function formatDate(d){
  if(!d) return "[Effective Date]";
  const x=new Date(d+"T00:00:00");
  return x.toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"});
}
function generateDocument(){
  const type=document.getElementById("documentType").value;
  const parties=document.getElementById("parties").value.trim()||"[Parties]";
  const termsRaw=document.getElementById("terms").value.trim();
  const date=formatDate(document.getElementById("date").value);
  const terms=termsRaw?termsRaw.split(";").map((t,i)=>`${i+1}. ${t.trim()}`).join("\n"):"1. [Enter terms and conditions]";
  let purpose="";
  if(type.includes("Employment")) purpose="This agreement records the employment arrangement, responsibilities, compensation and confidentiality obligations between the parties.";
  else if(type.includes("NDA")) purpose="This agreement establishes confidentiality obligations concerning information shared between the parties.";
  else if(type.includes("Lease")) purpose="This agreement records the principal terms governing the use and occupancy of the specified property.";
  else purpose="This agreement records the principal services, responsibilities, payment terms and obligations agreed by the parties.";
  const doc=`${type.toUpperCase()}
==============================

PARTIES
${parties}

EFFECTIVE DATE
${date}

PURPOSE
${purpose}

TERMS & CONDITIONS
${terms}

GENERAL PROVISIONS
The parties agree to review all information in this draft and make any required changes before use. Any applicable law, jurisdiction, signatures and supporting schedules should be completed according to the user's requirements.

SIGNATURES

Party 1: ______________________________

Party 2: ______________________________

Date: _________________________________

Generated by LegalEase – AI-assisted student project prototype.
`;
  document.getElementById("output").value=doc;
  document.getElementById("status").textContent="Generated";
}
function downloadTXT(){
  const text=document.getElementById("output").value;
  if(!text.trim()){alert("Generate a document first.");return;}
  const blob=new Blob([text],{type:"text/plain"});
  const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download="LegalEase_Document.txt"; a.click();
}
function printDocument(){
  if(!document.getElementById("output").value.trim()){alert("Generate a document first.");return;}
  window.print();
}
async function copyDocument(){
  const text=document.getElementById("output").value;
  if(!text.trim()){alert("Generate a document first.");return;}
  await navigator.clipboard.writeText(text); document.getElementById("status").textContent="Copied";
}
function clearAll(){
  ["parties","terms","date","output"].forEach(id=>document.getElementById(id).value="");
  document.getElementById("status").textContent="Ready";
}
